= Ardoonga Engine

# Ogłoszenia

Dobra, zmiana planów. 20 stycznia mam rzekomo umówioną rozmowę z kandydatem na własnego szefa.
Na końcu świata, 0.5 km od asfaltowej drogi i 2 autobusy bezpośrednie na dzień.
Żeby przetrwać w takim miejscu muszę natychmiast zgłupieć o 90%.
Taki skończony debil nie myśli, popełnia miliard błędów na sekundę (nie jak ja, że
zrobię głupi błąd, szukam go godzinę i zapominam zapisać rozwiązania), ma wykształcenie
wyższe doktora inżyniera, gluta pod nosem, poszarpaną koszulkę z jakimś wieśniackim tekstem,
i nie mówi tylko coś bełkocze. Nie planuje, bo to działka szefa tylko bezmyślnie wykonuje polecenia
i jest ekspertem w udawaniu, że pracuje. Zejście do takiego poziomu z samouka jest niemalże niemożliwe.

Oficjalnie inaczej się to nazywa ale jak tak pomyśleć. Jeśli rzucę okiem na kilka gier w stylu 
"klikam w linki i podwyższam statystyki", gdzieś zanotuję że wedle jednostki ludzkiej numer 000001 
to nieuczciwe, że wojownicy nie mogą rzucać czarów bojowych ale mogą wzmacniać nią przedmioty, 
jeśli zanotuję że wedle jednostki ludzkiej 000002 zmiana czegokolwiek jest niemożliwa bez 
osób technicznych, jeśli zaplanuję sobie że zbieram wiadomości w jednym miejscu o treści 
"gracz 1234 wykuł krótki miecz i włożył w to 100 energii, proszę odebrać mi surowce + energię 
oraz dać przedmioty" i potem bliżej nieokreślona liczba komputerów to liczy i zapisuje sobie, 
jeśli zakładam że najważniejszy jest dostęp do danych, dopiero do niego podłączam: czatboty,
aplikacje mobilne, gry 2D, "gry" przeglądarkowe i całą resztę. Jeśli mówię sobie "mam 128mb RAMu, 
współdzielony procesor jednowątkowy, normalne konto linuksa" i muszę coś z tym zrobić. Jeśli 
zaczynam od kiepskiej, bo kiepskiej ale makiety aplikacji. I jeśli przeglądam schemat pod kątem 
zgodności z istniejącymi grami pod kątem prawnym, bezpieczeństwa i wygody to na junior cokolwiek developera 
zdecydowanie się nie nadaję. Samouk poznaje ogólnie jak coś działa ale nie skupia się na szczegółach, 
zawodowy programista dokładnie na odwrót. Wie jak pracować w jednej technologi, z uwzględnieniem 
wszystkich szczegółów ale nie przejmuje się tym co do niego nie należy. Koniecznie musi też mieć 
chorobę psychiczną o nazwie "współpraca w grupie". Samouk najpierw stawia wymagania takiej grupie, 
być może pozwala jej na składanie własnych żądań i dopiero po spełnieniu ich wszystkich przyznaje 
innym prawo do współpracy ze sobą. Lata w szkole i lata grania w GTA Online nauczyły mnie, że 
praca z losowymi ludźmi niemal zawsze kończy się kompletną katastrofą. Ale łatwiej oskarżać mnie 
w zasadzie o wszystko.

== To już koniec ?

Więc zanim ostatecznie całkowicie zgłupieję chciałbym jeszcze dokończyć ostatni i jedyny projekt 
w swoim życiu.

https://www.figma.com/proto/MEitZEuwlWNTazjTUOC90L/Untitled?node-id=0-1&t=kIW7dNIbLNeMHUJC-1 →
jako skończony debil nie mogę używać profesjonalnych narzędzi bez wartego dziesiątki tysięcy 
złotych szkolenia ale w skrócie chodzi o to, że wpisuję "Google Material Design Components" 
i mam takie klocki, które dowolnie ustawiam na ekranie. Pomagają rozrysować sobie jak ma 
wyglądać strona. 

Do tego dochodzi ideologia, a więc mam smartfona z 2013 i laptop pamiętający 
czasy Windowsa XP. Jeśli jak każdy "profesjonalista" uruchomisz na tym tony animacji i JavaScriptu 
to masz praktycznie zagwarantowane wyrzucenie do pulpitu. Musisz stworzyć prosty design 
mając do dyspozycji różnej wielkości prostokąty, zaokrąglone kwadraty i ikony.

A że podstawowym celem samouka jest nauka, to myślałem by zrobić taki konkurs 
ze zwycięskim projektem włączonym do Ardoongi.

```Największą przeszkodą zawsze było zniżanie się do Waszego poziomu: 
myślenie, czy po wejściu w przeglądarkę wszystko będzie zrozumiałe, 
zastanawianie się jak mają wyglądać pliki konfiguracyjne, by nikt się nie pomylił ani niczego nie zepsuł,
Ograniczanie liczby kont na jakie trzeba się zalogować,
Zastanawianie się która z form logowania bezhasłowego będzie najprzyjemniejsza w użyciu dla użytkowników
I takie tam ...

Teraz zakładam sobie spam bota pod https://bsky.app/profile/ardoonga-bot.bsky.social 
// albo https://mastodon.social/@ArdoongaBOT
i wykorzystam do przechowywania wiadomości od wszystkich użytkowników.
Technicznie będę pisał sam do siebie.
// Potem i tak będzie trzeba przejść na HarperDB.
Potem zbiorę je programem na Github Actions (wcześniej na swoim komputerze) 
i może znajdą się jakieś praktyczne zalety Ideologii Otwartych Serwerów.
Crystal jest szczególnie dobry w tworzeniu ogromnych pętli i grupowaniu 
megabajtów wiadomości w mniejsze pliki.

Właściwie zawsze wychodziło mi to o wiele lepiej, niż warstwa wizualna
tak na szybko po prostu wyświetli się odpowiedni tekst na ekranie.
Zgodnie z Ideologią nie ma większego znaczenia czy piszę czatbota, grę 2D, 
czy wyświetlam pokolorowany tekst w przeglądarce. Najważniejsze, by to 
co chcę wyświetlić zawsze znajdowało si,ę w tym samym miejscu.

Przechodzę do katalogu "Protokół".
Trochę się pomiesza ale doc/pl będzie do książki "Jak stworzyć grę", 
a tutaj mam wersję powiedzmy techniczną.
```

Ze względu na brak czasu:

- Magia i Alchemia będą korzystać z tej samej metody "łączenia" 
składników ála Sowi Dom (najlepszy system magiczny i tak ma 
Avatar The Last Airbender).
- Nie robię unikalnych opisów, przedmiotów, ani żadnej zawartości gry.
- Nie wiem czy wyjdzie Forum i Wiadomości Prywatne.

Ardoonga pomoże Ci stworzyć internetową tekstową grę RPG. 
Nie musisz konfigurować żadnych serwerów, ani za nic płacić. 
Wszystko zrobi się automatycznie.

CAUTION: Niestabilne. Wszystko co tu pisze może się zmienić w każdej chwili.

Zazwyczaj zaczynamy od wybrania rasy i klasy swojej postaci. Dodajmy kilka z nich.

Ale najpierw zacznijmy od najważniejszego.

[qanda]
Gdzie wrzucać swoje pliki ?::
Utwórz nowy podfolder w folderze extensions.
Ja nazwę swoje rozszerzenie Archipelag.
//CAUTION: folder src zawiera pliki odpowiedzialne za działanie programu.
//Gdzie znajdę ściągawkę jak pisać pliki ?::
//https://solr.apache.org/guide/8_10/meta-docs/asciidoc-syntax.html

include::doc/pl/zapis_zmiennych.adoc[]
