= Opis

Funkcja tworzca nowe oraz modyfikujca istniejce statystyki. 
Mo偶e modyfikowa dziaanie innych czstek. 
Efekty jakie powoduje s do siebie dodawane. 
Jest odpowiednikiem substancji chemicznej w naszym wiecie.

Identyfikatory mog zawiera znaki [a-z] oraz -

= Przykad

Zgodnie z tradycyjn receptur najprostszy przepis na 
mikstur zdrowia to 3 uncje czerwonego kwiata i 1 uncja 
neutralnego zielska.

Silnik pozwala nam na dodanie efekt贸w dla ka偶dej uncji.

Tekst rozpoczty od [mixer id nazwa] pozwala nam modyfikowa 
dziaanie podstawowych statystyk jeli w miksturze zawarty jest 
skadnik o wskazanym identyfikatorze.

Mo偶emy te偶 u偶ywa warunk贸w [if ...] 
sprawdzanych w czasie zbierania roliny:

- precipitation = rednia wilgotno
- temperature = rednia temperatura

czymy je sowem AND oraz jednym z 5 s贸w:

- gte = wiksze lub r贸wne
- lte = mniejsze lub r贸wne
- eq = r贸wne
- lt = mniejsze ni偶
- gt = wiksze ni偶

```adoc
id:: illani
hex:: 72010F #https://www.npmjs.com/package/hex-color-to-color-name

偶ycie_max:: -15
偶ycie:: 6

[if precipitation gte 1500 AND temperature lte 20]
hex:: FF4040
smell:: 
偶ycie_max:: +20

[mixer id neutral]
偶ycie_max:: +5
偶ycie:: -3
```

Zwizki chemiczne zawarte w czerwonym kwiatku 
zwiksz moje aktualne HP ale znaczco zmniejsz 
maksymalne HP.

Po wymieszaniu z zioem neutralnym warto lecznicza 
si co prawda pogorszy ale zniknie szansa na zatrucie organizmu.

Istnieje te偶 odmiana wystpujca w wilgotnym i niezbyt gorcym 
rodowisku. R贸偶ni si kolorem oraz zapachem i delikatnie zwiksza maksymalne 
偶ycie (-15+20 daje +5 maksymalnego HP na uncj oraz +6 aktualnego HP).

Kombinacje s w zasadzie nieskoczone.

Specyfikacja nie definiuje czy ukryjesz t informacj, czy mo偶e poka偶esz graczom. 
U mnie statystyki bd si pokazyway wraz z postpem w zielarstwie.

== Magia

Wyobra藕my sobie, 偶e illani jest znakiem alchemicznym. 

Majc dostp do odpowiedniego warsztatu i magicznego pergaminu 
mo偶esz zapisa go, co zamieni kawaek pergaminu w jednorazowe zaklcie.

Podobnie jak w Gothicu prawdziwa magia tak na prawd nie istnieje. 
Czarodzieje maj po prostu przy sobie takie runy-zwoje wielokrotnego u偶ytku.

Zaraz, zaraz. Czy to znaczy, 偶e mam dostp do zielska zamra偶ajcego 
powierzchni, na kt贸r wylej mikstur ? A czemu by nie ?

```adoc
id:: dziadek-mr贸z

status:: frozen
```

Oto wz贸r na czstk Dziadek Mr贸z, kt贸ra 
doda status frozen do wszystkiego czego dotknie.

Mo偶esz zrobi z niej czar Dziadek Mr贸z albo nazwa 
czar po swojemu.
